### ISSUE TITLE
example usage does not work out of the box

### ISSUE THREAD

**Issue by alexanderniebuhr** [harlan-zw/changelogd#1]
Apologise in advance for the short issue report without any information. I am just between two meetings, but I wanted to give that a try and did not come far.

```sh
alexanderniebuhr@Alexanders-MacBook-Pro ~ % npx changelogd@latest @antfu/eslint-config --from 0.20.0          
file:///Users/alexanderniebuhr/.npm/_npx/a9d4f5a5d06aca2f/node_modules/@changelogd/core/dist/index.mjs:5
import { coerce, lt } from 'semver';
         ^^^^^^
SyntaxError: Named export 'coerce' not found. The requested module 'semver' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'semver';
const { coerce, lt } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)

Node.js v18.0.0
```

**Comment by harlan-zw** [comment]
Hey @alexanderniebuhr! Thanks for trying it out.

I shipped this at an ungodly hour last night so did not test it very thoroughly outside of the unit tests, so thanks for bringing that to my attention.

I've pushed a fix and updated the documentation. 

If you'd like to test it use one of the below, that package version doesn't actually have a changelog diff it seems for 0.20.0..

**Fetching CHANGELOG.md from Github**

```sh
npx changelogd@latest ohmyfetch --from 0.4.0
```

**Fetching CHANGELOG.md from NPM**

```sh
npx changelogd@latest consola --from 2.13.0
```

**Fetching Github Releases**

```sh
npx changelogd@latest nuxt-windicss --from 2.13.0
```

**Comment by alexanderniebuhr** [comment]
Thanks for the update. 
I just tested them, and the first two examples look totally fine. Very cool tool.

However I still get an issue with the third one.
```
alexanderniebuhr@Alexanders-MacBook-Pro ~ % npx changelogd@latest nuxt-windicss --from 2.3.0 

 ERROR  coerce is not a function                                                                                      13:47:58

  at changelogd (.npm/_npx/a9d4f5a5d06aca2f/node_modules/@changelogd/core/dist/index.mjs:126:11)
  at async main (.npm/_npx/a9d4f5a5d06aca2f/node_modules/@changelogd/cli/dist/index.mjs:17:15)
```

**Comment by harlan-zw** [comment]
Damn ESM / CJS issues! Haha, well I think it should be fixed now..

```
npx changelogd@0.1.2 nuxt-windicss --from 2.3.0
```
